name: Foundry CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Foundry compilation cache
        uses: actions/cache@v3
        with:
          path: |
            out
            cache
          key: compilation-${{ github.base_ref || github.ref_name }}

      - name: Run tests
        run: forge test

      - name: Install halmos
        run: python3 -m pip install --upgrade halmos

      - name: Run halmos
        run: halmos --function testProve --loop 4
